kubernetes:
  host: https://kubernetes.default

helloworld:
  namespace: default
  image:
    name: tum-tum/hello-world
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress
